### ISSUE TITLE
[BUG] Can't see links in mixture graph

### ISSUE THREAD

**Issue by ShockWave2048** [alelievr/Mixture#29]
Hi!

I don't see any links for mixture 

- I open github project in Unity 
- and open mixture file, in graph window, 
- can't see any links between nodes.

Windows
Unity Version: 2021.1.11f1
R3950, GTX1080, 32Gb

What i do wrong?
Thanks for answer!

Screen - https://prnt.sc/15d6nny

**Comment by alelievr** [comment]
Hello,

Does it work if you create a new mixture asset? (static or realtime)

**Comment by ShockWave2048** [comment]
With new mixture it's works.
![Screenshot_2](https://user-images.githubusercontent.com/800625/121874950-8cc7b080-cd10-11eb-914d-d590a308ed71.jpg)

**Comment by alelievr** [comment]
Okay, it's probably an old broken mixture asset in the project, I'll do a cleanup pass

**Comment by alelievr** [comment]
I did a cleanup pass on master, all the graphs should be fine now :)
