### ISSUE TITLE
[BUG] "graph.onGraphChanges += ProcessGraphWhenChanged;" accumulates infinitely

### ISSUE THREAD

**Issue by danholbertunity** [alelievr/Mixture#30]
**What happened?**
You can get into a situation where the graph runs an arbitrary number of times upon changes (instead of just one time).

**To Reproduce**
Open a Mixutre graph.
Close the graph editor.
Open the same graph again.
Attach a debugger and put a breakpoint in MixtureGraphProcessor.ProcessNodeList
Make a change to your graph that would trigger it to run again.
Notice that your breakpoint is hit twice.
Close the graph editor and repeat the process.
Notice that your breakpoint is hit three times.
And so on.

**Setup:**
Windows
  "version": "0.3.0",
  "unity": "2020.3",

**Comment by alelievr** [comment]
Thanks for the bug report, the fix seems straightforward, I'll fix it soon

**Comment by alelievr** [comment]
Fixed in https://github.com/alelievr/Mixture/commit/b5238bec0c13b9fb9c1abdb59fe5b13b5def1106

**Comment by danholbertunity** [comment]
Great. Thank you!
