### ISSUE TITLE
[BUG] Crash when using other graph based on NodeGraphProcessor

### ISSUE THREAD

**Issue by dimozaprianov** [alelievr/Mixture#31]
**What happened?**
Crashes here (there are several instances of this code)
```
		static bool IsCompatibleWithRealtimeGraph(BaseGraph graph)
			=> (graph as MixtureGraph).type == MixtureGraphType.Realtime;
```
Crashes when trying to create new node in no-MixtureGraph. For me it is obvious the code here is not shielded in those cases and this seems as a problem.

**Comment by alelievr** [comment]
Thanks for the bug report :) 

it should be fixed in master now (example: https://github.com/alelievr/Mixture/blob/master/Packages/com.alelievr.mixture/Runtime/Nodes/Utils/SelfNode.cs#L69)
