### ISSUE TITLE
Requirements in README do not match package.json.

### ISSUE THREAD

**Issue by Haruma-K** [alelievr/Mixture#34]
**What happened?**
I'm trying to use Mixture with Unity2020.2.7f1.  
According to the README, Mixture requires Unity 2020.2 beta or higher.

> You need at least a Unity 2020.2 beta

However, according to the latest version of the package.json, Unity 2020.3 or higher is required.
It seems that the package.json has been changed with the following commit.

https://github.com/alelievr/Mixture/commit/51ec1a3653d973f1adea09b4f16769e873790fd4#diff-9927e926cd159cd6051ef323b5d6f6ec5e143369ae77390ec2f0a174e22443a8

Is Mixture compatible with Unity2020.2?
I've installed it from GitHub and it looks like 0.4.0 is working fine in Unity2020.2.7f1.

**Setup:**
 - OS: [e.g. Mac]
 - Unity Version: [e.g. 2020.2.7f1]

Thanks for your great software!

**Comment by alelievr** [comment]
Thanks, I updated the readme

> Is Mixture compatible with Unity2020.2?
Yes, but it's retro-compatibility, technically it will work better with 2020.3
